name: to_do_abstracta_app
version: 1.0.0+1
description: "A new Flutter project."

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  http: ^1.1.0
  uuid: ^4.1.0
  intl: ^0.18.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_staggered_animations: ^1.1.1
  flutter_platform_widgets: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true