// Mocks generated by Mockito 5.4.5 from annotations
// in to_do_abstracta_app/test/presentation/pages/task_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:to_do_abstracta_app/domain/entities/task.dart' as _i5;
import 'package:to_do_abstracta_app/domain/models/task_form_data.dart' as _i3;
import 'package:to_do_abstracta_app/domain/usecases/llm_usecases.dart' as _i6;
import 'package:to_do_abstracta_app/domain/usecases/task_usecases.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskStatistics_0 extends _i1.SmartFake
    implements _i2.TaskStatistics {
  _FakeTaskStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskFormData_1 extends _i1.SmartFake implements _i3.TaskFormData {
  _FakeTaskFormData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskUsecases extends _i1.Mock implements _i2.TaskUsecases {
  MockTaskUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Task>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<_i5.Task?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i4.Future<_i5.Task?>.value(),
      ) as _i4.Future<_i5.Task?>);

  @override
  _i4.Future<void> createTask(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTaskStatus(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleTaskStatus,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.TaskStatistics> getTaskStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getTaskStatistics,
          [],
        ),
        returnValue: _i4.Future<_i2.TaskStatistics>.value(_FakeTaskStatistics_0(
          this,
          Invocation.method(
            #getTaskStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.TaskStatistics>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);

  @override
  _i4.Future<List<_i5.Task>> searchTasks(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchTasks,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);
}

/// A class which mocks [LLMUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMUsecases extends _i1.Mock implements _i6.LLMUsecases {
  MockLLMUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured => (super.noSuchMethod(
        Invocation.getter(#isConfigured),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i3.TaskFormData> generateCompleteTaskFromTitle(String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCompleteTaskFromTitle,
          [title],
        ),
        returnValue: _i4.Future<_i3.TaskFormData>.value(_FakeTaskFormData_1(
          this,
          Invocation.method(
            #generateCompleteTaskFromTitle,
            [title],
          ),
        )),
      ) as _i4.Future<_i3.TaskFormData>);
}
